### PR TITLE
Add Medium as a possible social link

### PR DESCRIPTION
**Pull request by felipythondev**
The idea is add Medium as a social link because it's common for people use it as their blog, so they could have their blogs posts linked in their resumes.

TODO: I found a generic icon for Medium but it's not like the other ones, if you have something better just let me know.

image

### CODE REVIEW

**Comment by jglovier** [comment]
@lipemorais great idea!! I love Medium and more and more authors are publishing their writing both on Medium and their blog.

Could you please post a screenshot of the visual change? 🙏

**Comment by jglovier** [comment]
@lipemorais do you have a vector editor you could use to modify the style of that logo to match the other social media icons? It looks pretty out of place as is. If not I can add it to my todo list to push a commit to your branch as long as you have "Allow edits from Maintainers" checked in the sidebar of this PR.

**Comment by felipythondev** [comment]
I don't have and I don't know how to use a vector editor. This is a point that I would like to have your help.

"Allow edits from Maintainers" is checked ✅

**Comment by jglovier** [comment]
@lipemorais I pushed a reworked version of the icon so it looks like this now:

image

I think you need to update the branch from master, but once you do that this should be ready to merge. :zap:

**Comment by jglovier** [comment]
Nevermind – merge from master was unnecessary. I got this merged in now. Thanks again for your contribution @lipemorais!! :tada:

**Pull request merged**
