### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by javierorange**

### CODE REVIEW

**Comment by jglovier** [comment]
@javierorange if you are trying to customize this for your own use, you'll need to fork the repository first to your own account, then you can commit directly there.

**Comment by javierorange** [comment]
I think I messed up! Sorry about that! And thank you for sharing the
template, it is great!

**Comment by jglovier** [comment]
No worries! :heart: :+1:

**Comment by javierorange** [comment]
I think I managed :-)

http://javierorange.github.io/myresume/

**Comment by jglovier** [comment]
Good work @javierorange! Looks great.

**Pull request closed without merging**
