### PR TITLE
Add Outside Interests section

### PR DESCRIPTION
**Pull request by antgel**
Covers Issue #32 that I just opened. Hope it's useful. :)

### CODE REVIEW

**Comment by jglovier** [comment]
Thanks for the PR @antgel, but I'm going to pass on incorporating this at this point per my response in #32. 🙇

**Comment by jglovier** [comment]
Reopening based on further discussion in #32. I think this is reasonable, but I'd like the config option to include it to default to false. 

Like I said I feel pretty strongly that this type of thing doesn't belong in a resume, largely because personal interests sections can often lead to confirmation bias about candidates in hiring processes that often do not favor under-represented individuals, and also because it's irrelevant to completely hiring IMO.

That being said, if someone wants to include it, that's their prerogative. But I'd prefer to default to off.

**Comment by antgel** [comment]
Cool, I'll update the PR. :) At the risk of repeating myself, there are other sections that currently default to {{true}}, that are probably no more important / relevant than outside interests, for the same reasons you mention. I'd urge you to consider those as well. But for sure that's no reason to block this PR.

**Comment by antgel** [comment]
PR updated to default to not show outside interests by default.

**Comment by jglovier** [comment]
>At the risk of repeating myself, there are other sections that currently default to {{true}}, that are probably no more important / relevant than outside interests

Which are some of the sections you are thinking of?

**Comment by jglovier** [comment]
And thanks again for the PR, and for the discussion. :zap:

**Comment by antgel** [comment]
Pleasure, thanks for a cool template!

I was thinking of:
- Image
- Social links
- Associations

All of which *might* be relevant, but not universally IMHO.

**Pull request merged**
