### PR TITLE
YAML for filling resume content

### PR DESCRIPTION
**Pull request by kks32**
Hi @jglovier Thanks for the wonderful resume template. I have adopted your template to pull the resume content from YAML documents. This separates the data from the template. The content can be filled in `_data` folder in different YAML files and the `_layout/resume.html` iterates through the file to render the final output. I hope this is useful.

### CODE REVIEW

**Comment by kks32** [comment]
I think this might be inline with the discussion related to PR #3

**Comment by aboutte** [comment]
@kks32 was just about to look into separating the data from the template and was happy to see this PR.  👍 

@jglovier is there anything stopping you from merging this in (besides the conflict)?

**Comment by jglovier** [comment]
@aboutte @kks32 very much apologies for the very long delay in responding to this PR. I'm ashamed at how long I have let this sit without response. 😞 I've been devoting all of my attention elsewhere and simply have not had any attention to give to this project in the past year. 

I'd been waiting for some time to actually give it a proper review and check out the approach here, and to decide whether it's something I'm interested in for this project. My goal is to make it as simple and easy to use for folks with minimal coding knowledge who want to get their own site up quickly and easily. If you can edit a basic HTML file right now you can do that. 

So my only concern with this approach is that separating the structure might be confusing for folks who don't really understand what YAML data is. I realize that it's already used in basic Jekyll projects, but I'd like this project to be accessible to folks who don't even really get Jekyll yet.

That being said, this is a really great solution for separating the data from the markup, and perhaps it could even do the opposite of what my concern is by making it easier to edit. I think we'll just have to be clear in the README about what is happening with the data and how to edit it.

Reviewing now and will leave some notes in my review.

Thanks for your patience!! 😊

**Review by jglovier — APPROVED** [review]
Yeah, this is great. Thanks again, and apologies on the very long review time. :blush:

:metal: :sparkles: :heart:

**Comment by jglovier** [comment]
@kks32 the conflict is blocking me from merging, and I can't resolve it without the "[Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)" setting on this pull request checked (in the sidebar). Could you please check that so I can resolve the merge conflict? Or if you'd prefer to resolve it, that'd be fine too.

image

**Comment by kks32** [comment]
@jglovier Thank you. I have given you the permission to edit the pull request. Thank you for this awesome template.

**Comment by jglovier** [comment]
Thanks again @kks32!

**Pull request merged**
